### ISSUE TITLE
roscd: Not a directory

### ISSUE THREAD

**Issue by Danmou** [MetroRobots/ros_command#1]
When I execute `roscd` in a ROS2 workspace I get the following error:
```
bash: cd: /home/daniel/ros_ws/install/setup.bash: Not a directory
```
It happens because the `roscd` command attempts to run `cd $(get_current_setup_bash)`. When I run `roscd some_package` I get the same error, but the command works.

**Comment by DLu** [comment]
Looks like I didn't test that path! Thanks for the report. 

Where do you think `roscd` (without args) should go? Workspace root? COLCON_PREFIX_PATH?

**Comment by Danmou** [comment]
> Where do you think `roscd` (without args) should go? Workspace root? COLCON_PREFIX_PATH? 

I think colcon doesn't really have a concept of workspace root (since the build, install and src dirs can be anywhere), so I think the src dir would be the most useful.
